### PR TITLE
refactor python codes

### PR DESCRIPTION
**Pull request by jnozsc**
## 📝 関連issue

なし

## ⛏ 変更内容

- refactor python codes

### CODE REVIEW

**Comment by jnozsc** [comment]
cc @yokinist

**Comment by kaizumaki** [comment]
@jnozsc Thanks for your suggestion about the code! LGTM, but currently, the screenshot function is not running. Sorry, I close this PR.

**Comment by jnozsc** [comment]
no problem. is `/ui-test/ogp_screenshot.py` on staging branch? I can create a similar pull request for that

**Comment by halsk** [comment]
@jnozsc , Yes, the script is running on the `staging`  branch. Thank you for supporting!

**Pull request closed without merging**
