### PR TITLE
[i18n] Update translation of 合計(in en and zh-tw)

### LINKED ISSUE #1227: 日本語表示されました
## 起こっている問題 / The Problem
- 日本語表示されました

## スクリーンショット / Screenshot

chrome_lyB3ZS0YAT

chrome_c6qa45cjxk

## 動作環境・ブラウザ / Environment
- Windows
- Chrome

### PR DESCRIPTION
**Pull request by kiecoo**
## 📝 関連issue / Related Issues

- #680 
- close #1227 

## ⛏ 変更内容 / Details of Changes

Improve :  "`{date}の合計` without translation" (Now it's the same as [translation-wordstable](https://docs.google.com/spreadsheets/d/1aksSfWIXE_L3rFYFjHz9xtVhh0n7ealMQ0eEz8GGPlw/edit#gid=0))
- en: `{date}の合計` => `Total of %{date}`
- zh-tw: `{date}の合計` => `%{date} 的合計` 
- zh-cn: `{date}の合計` => `%{date} 当日合计` 
- ko: `{date}の合計` => `%{date} 합계` 
- ja-basic: `{date}の合計` => `%{date} ぜんぶで`
截圖 2020-03-12 下午11 20 34

## 📸 スクリーンショット / Screenshots

截圖 2020-03-12 下午6 26 27
截圖 2020-03-12 下午6 21 23

### CODE REVIEW

**Comment by PichuChen** [comment]
zh-TW: {date} 的合計 maybe more near the Japanese meaning on wording?

Btw, there is the translation table: https://docs.google.com/spreadsheets/d/1aksSfWIXE_L3rFYFjHz9xtVhh0n7ealMQ0eEz8GGPlw/edit#gid=0

**Comment by PichuChen** [comment]
Ref: #1227

**Comment by kiecoo** [comment]
> Ref: #1227

thank you

**Comment by kiecoo** [comment]
> zh-TW: {date} 的合計 maybe more near the Japanese meaning on wording?
> 
> Btw, there is the translation table: https://docs.google.com/spreadsheets/d/1aksSfWIXE_L3rFYFjHz9xtVhh0n7ealMQ0eEz8GGPlw/edit#gid=0


- `zh-TW: {date} 的合計` is good , I already updated it  as your suggestion :) 
- The lastest commit I did     is the same as translation-wordstable that you shared

Thank you so much for translation table :)

**Pull request merged**
