### PR TITLE
enable to change data label for TimeStackedBarChart

### LINKED ISSUE #1718: Use :items data for TimeStackedBarChart.vue
## 改善詳細 / Details of Improvement
- When cursor hover on Bar of Time Stack Bar Chart, it will show "都內" or "その他" now
- But this two line is fixed in TimeStackedBarChart.vue
- So you can't modify it from attribution of time-stacked-bar-chart
- It will make TimeStackedBarChart.vue more useable

## スクリーンショット / Screenshot (Before)
螢幕快照 0002-03-18 02 05 55
螢幕快照 0002-03-18 02 10 27

螢幕快照 0002-03-18 02 10 39
螢幕快照 0002-03-18 02 10 33

## 期待する見せ方・挙動 / Expected behavior (After)
螢幕快照 0002-03-18 02 01 51

### PR DESCRIPTION
**Pull request by mmfiber**
## 👏 解決する issue / Resolved Issues
- close #1718 

## ⛏ 変更内容 / Details of Changes
- enable to add more than 2 data to `TimeStackedBarChart.vue`
- enable to change data labels 

## 📸 スクリーンショット / Screenshots
- Before
  check #1718 

- After
image

### CODE REVIEW

**Comment by PichuChen** [comment]
I think we can use items as default source?

**Comment by mmfiber** [comment]
@PichuChen 
> I think we can use items as default source?

I don't think so because items and dataLabels are slightly different.
```
items: [this.$t('都内発生（疑い例・接触者調査）'), this.$t('その他（チャーター便・クルーズ船）')]
dataLables[this.$t('都内'), this.$t('その他')]
```

**Comment by PichuChen** [comment]
> @PichuChen
> 
> > I think we can use items as default source?
> 
> I don't think so because items and data-labels are slightly different.
> 
> ```
> items: [this.$t('都内発生（疑い例・接触者調査）'), this.$t('その他（チャーター便・クルーズ船）')]
> data-lables: [this.$t('都内'), this.$t('その他')]
> ```

I think you are right

**Comment by kaizumaki** [comment]
I think this is a great implementation!  Can I review it?

**Pull request merged**
