### PR TITLE
Bump actions/cache from v1 to v2

### PR DESCRIPTION
**Pull request by imbsky**
Closes: #4536

We just released v2. That includes a lot of improvements.
https://github.com/actions/cache/releases/tag/v2.0.0

### CODE REVIEW

**Comment by imbsky** [comment]
By the way, the old path used for caching doesn't exist in Windows, so you need to set the correct path using the command `yarn cache dir`.

**Comment by MasaGon** [comment]
@imbsky Only `screenshot.yml` runs on windows. Does it have any side effect for ubuntu and MacOS?

```
run: echo "::set-output name=dir::$(yarn cache dir)"
```

**Comment by imbsky** [comment]
Hm, what do you mean? There are no side effects here. The problem is to keep such a mutable state you have to take care of. Don't you think so?

**Comment by MasaGon** [comment]
@imbsky You are right. I just wanted to confirm there is no side effect. No other meaning.

**Comment by imbsky** [comment]
Huh, I see. This is a trivial note to make things clearer. You can ignore it 🙂

That line does the following:
https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter

So, we can write the exact same thing in JavaScript and execute it via the `node` command. Like follows:

```javascript
const { spawn } = require("child_process");

const yarn = spawn("yarn", ["cache", "dir"]);

yarn.stdout.on("data", (data) => {
  console.log(`::set-output name=dir::${data}`);
});
```

**Pull request merged**
