### PR TITLE
English wording update for 新型コロナ受診相談窓口 による相談結果

### LINKED ISSUE #1287: [i18n] English wording: 相談結果の箇所の表記の変更及び簡素化
## 改善詳細 / Details of Improvement
- 新型コロナ受診相談窓口 による相談結果とその下のフローの英語表記を少しシンプルにしたほうが分かりやす課と思います。

## スクリーンショット / Screenshot
image

## 期待する見せ方・挙動 / Expected behavior
image

## 動作環境・ブラウザ / Environment
- Windows 10
- Chrome 

## 補足情報
翻訳用スプレッドシートは、「You need permission」と表示されてアクセスできず、確認できておりません。

### PR DESCRIPTION
**Pull request by dg4101**
## 📝 関連issue / Related Issues

- close #1287 

## ⛏ 変更内容 / Details of Changes

- According to call {advisory}" -> After your inquiry with {advisory}
- You are {ifRequired} to be tested -> Test {ifRequired}

## 📸 スクリーンショット / Screenshots
変更前
image

変更後
image

As the translation table is not accessible with this message "You need permission" , I was not able to verify what's said in the table.

### CODE REVIEW

**Comment by MaySoMusician** [comment]
Thank you for your contribution!
The original translation table is closed due to Google's share count limits. We're in [a new sheet](https://docs.google.com/spreadsheets/d/1avT6QGInyQseYjoc_TxL8RPZfutyvrv4BtJkXfk1Nko/edit?usp=sharing).
And we're currently checking if the translations is up-to-date with those in the spreadsheet, so the spreadsheet is locked.

- Could you divide the translation dictionary (`<i18n> ~ </18n>` containing `ja` key etc.) in the `*.vue` into `*.i18n.json` ?
- Could you omit updating commits for `*.i18n.json` because we're currently dealing with in #1312 . I'll surely tell the contributor in charge of each file in #1312 what you wanted to update
  - `components/TimeStackedBarChart.i18n.json`
  - `components/flow/FlowPc.i18n.json`
  - `components/flow/FlowPcRequired.i18n.json`
  - `components/flow/FlowSpAccording.i18n.json`
  - `pages/index.i18n.json`

**Comment by nard-tech** [comment]
@dg4101
ご協力ありがとうございます．この PR の内容は #1392 に merge して取り込みますので，こちらの PR は close をお願いします．

**Comment by nard-tech** [comment]
@dg4101
やっぱり #1392 に取り込むのはなしにします．すみません．
この PR は close せずそのままにしてください．

**Comment by dg4101** [comment]
Commits are revered for `*i18n.json`
For `*.vue` files `<i18n> ~ </18n>` split into `*.i18n.json`

Could you take a look? I wasn't sure if this is what was expected but if further changes are required, please let me know.

**Comment by nard-tech** [comment]
@dg4101
Thank you for your contribution.
We are now moving `<i18n> ~ </i18n>` in `*.vue` files into `*.i18n.json`.
So your commits looks nice!

**Pull request merged**
